[package]
name = "magic-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = "0.6"
dotenvy = "0.15"
tracing = "0.1"
subprocess = "0.2"
sysinfo = "0.35"
tracing-subscriber = "0.3"
tokio = { version = "1.0", features = ["full"] }
